"""Tests for PR comment reporter (F5.1)."""

from __future__ import annotations

from checkagent.ci.quality_gate import GateResult, GateVerdict, QualityGateReport
from checkagent.ci.reporter import RunSummary, generate_pr_comment
from checkagent.core.cost import CostReport, ModelCost


class TestRunSummary:
    """Tests for RunSummary data class."""

    def test_pass_rate(self):
        s = RunSummary(total=10, passed=8, failed=2)
        assert s.pass_rate == 0.8

    def test_pass_rate_zero_total(self):
        s = RunSummary(total=0, passed=0, failed=0)
        assert s.pass_rate == 0.0

    def test_to_dict(self):
        s = RunSummary(total=5, passed=4, failed=1, duration_s=1.234)
        d = s.to_dict()
        assert d["total"] == 5
        assert d["passed"] == 4
        assert d["pass_rate"] == 0.8
        assert d["duration_s"] == 1.23


class TestGeneratePRComment:
    """Tests for Markdown PR comment generation."""

    def test_minimal_comment(self):
        comment = generate_pr_comment()
        assert "## CheckAgent Test Report" in comment
        assert "Generated by" in comment

    def test_custom_title(self):
        comment = generate_pr_comment(title="My Report")
        assert "## My Report" in comment

    def test_test_summary_section(self):
        summary = RunSummary(total=10, passed=9, failed=1, duration_s=5.0)
        comment = generate_pr_comment(test_summary=summary)
        assert "### Test Results" in comment
        assert "| Total tests | 10 |" in comment
        assert "| Passed | 9 |" in comment
        assert "| Failed | 1 |" in comment
        assert "90.0%" in comment

    def test_regressions_listed(self):
        summary = RunSummary(
            total=10, passed=8, failed=2,
            regressions=["test_foo", "test_bar"],
        )
        comment = generate_pr_comment(test_summary=summary)
        assert "Regressions detected" in comment
        assert "`test_foo`" in comment
        assert "`test_bar`" in comment

    def test_quality_gates_section(self):
        report = QualityGateReport(
            results=[
                GateResult(
                    metric="accuracy",
                    verdict=GateVerdict.PASSED,
                    actual=0.95,
                    threshold=0.90,
                    direction="min",
                ),
                GateResult(
                    metric="cost",
                    verdict=GateVerdict.BLOCKED,
                    actual=0.75,
                    threshold=0.50,
                    direction="max",
                    message="over budget",
                ),
            ]
        )
        comment = generate_pr_comment(gate_report=report)
        assert "### Quality Gates" in comment
        assert "accuracy" in comment
        assert "cost" in comment
        assert ":x:" in comment
        assert ":white_check_mark:" in comment

    def test_all_gates_passed_status(self):
        report = QualityGateReport(
            results=[GateResult(metric="a", verdict=GateVerdict.PASSED)]
        )
        comment = generate_pr_comment(gate_report=report)
        assert "All quality gates passed" in comment

    def test_blocked_status(self):
        report = QualityGateReport(
            results=[GateResult(metric="a", verdict=GateVerdict.BLOCKED)]
        )
        comment = generate_pr_comment(gate_report=report)
        assert "1 quality gate(s) blocked" in comment

    def test_cost_section(self):
        cost = CostReport(
            run_count=5,
            total_input_tokens=1000,
            total_output_tokens=500,
            total_cost=0.1234,
            per_model={"gpt-4o": ModelCost(model="gpt-4o", input_tokens=1000, output_tokens=500, cost=0.1234)},
        )
        comment = generate_pr_comment(cost_report=cost)
        assert "### Cost Summary" in comment
        assert "$0.1234" in comment
        assert "1,500" in comment  # total tokens
        assert "gpt-4o" in comment

    def test_all_sections_combined(self):
        summary = RunSummary(total=10, passed=10)
        gate_report = QualityGateReport(
            results=[GateResult(metric="a", verdict=GateVerdict.PASSED)]
        )
        cost = CostReport(run_count=1, total_cost=0.01)
        comment = generate_pr_comment(
            test_summary=summary,
            gate_report=gate_report,
            cost_report=cost,
        )
        assert "### Test Results" in comment
        assert "### Quality Gates" in comment
        assert "### Cost Summary" in comment

    def test_errors_shown_when_nonzero(self):
        summary = RunSummary(total=5, passed=3, failed=1, errors=1)
        comment = generate_pr_comment(test_summary=summary)
        assert "| Errors | 1 |" in comment
