"""Tests for PR comment reporter (F5.1)."""

from __future__ import annotations

from checkagent.ci.quality_gate import GateResult, GateVerdict, QualityGateReport
from checkagent.ci.reporter import TestRunSummary as CITestRunSummary
from checkagent.ci.reporter import generate_pr_comment
from checkagent.core.cost import CostReport, ModelCost
from checkagent.eval.aggregate import AggregateResult, RegressionResult
from checkagent.eval.aggregate import RunSummary as EvalRunSummary
from checkagent.safety.compliance import CategorySummary, ComplianceReport
from checkagent.safety.taxonomy import SafetyCategory, Severity


class TestCIRunSummary:
    """Tests for TestRunSummary (CI test results)."""

    def test_backward_compat_alias(self):
        from checkagent.ci.reporter import RunSummary

        assert RunSummary is CITestRunSummary

    def test_pass_rate(self):
        s = CITestRunSummary(total=10, passed=8, failed=2)
        assert s.pass_rate == 0.8

    def test_pass_rate_zero_total(self):
        s = CITestRunSummary(total=0, passed=0, failed=0)
        assert s.pass_rate == 0.0

    def test_to_dict(self):
        s = CITestRunSummary(total=5, passed=4, failed=1, duration_s=1.234)
        d = s.to_dict()
        assert d["total"] == 5
        assert d["passed"] == 4
        assert d["pass_rate"] == 0.8
        assert d["duration_s"] == 1.23


class TestGeneratePRComment:
    """Tests for Markdown PR comment generation."""

    def test_minimal_comment(self):
        comment = generate_pr_comment()
        assert "## CheckAgent Test Report" in comment
        assert "Generated by" in comment

    def test_custom_title(self):
        comment = generate_pr_comment(title="My Report")
        assert "## My Report" in comment

    def test_test_summary_section(self):
        summary = CITestRunSummary(total=10, passed=9, failed=1, duration_s=5.0)
        comment = generate_pr_comment(test_summary=summary)
        assert "### Test Results" in comment
        assert "| Total tests | 10 |" in comment
        assert "| Passed | 9 |" in comment
        assert "| Failed | 1 |" in comment
        assert "90.0%" in comment

    def test_regressions_listed(self):
        summary = CITestRunSummary(
            total=10, passed=8, failed=2,
            regressions=["test_foo", "test_bar"],
        )
        comment = generate_pr_comment(test_summary=summary)
        assert "Regressions detected" in comment
        assert "`test_foo`" in comment
        assert "`test_bar`" in comment

    def test_quality_gates_section(self):
        report = QualityGateReport(
            results=[
                GateResult(
                    metric="accuracy",
                    verdict=GateVerdict.PASSED,
                    actual=0.95,
                    threshold=0.90,
                    direction="min",
                ),
                GateResult(
                    metric="cost",
                    verdict=GateVerdict.BLOCKED,
                    actual=0.75,
                    threshold=0.50,
                    direction="max",
                    message="over budget",
                ),
            ]
        )
        comment = generate_pr_comment(gate_report=report)
        assert "### Quality Gates" in comment
        assert "accuracy" in comment
        assert "cost" in comment
        assert ":x:" in comment
        assert ":white_check_mark:" in comment

    def test_all_gates_passed_status(self):
        report = QualityGateReport(
            results=[GateResult(metric="a", verdict=GateVerdict.PASSED)]
        )
        comment = generate_pr_comment(gate_report=report)
        assert "All quality gates passed" in comment

    def test_blocked_status(self):
        report = QualityGateReport(
            results=[GateResult(metric="a", verdict=GateVerdict.BLOCKED)]
        )
        comment = generate_pr_comment(gate_report=report)
        assert "1 quality gate(s) blocked" in comment

    def test_cost_section(self):
        cost = CostReport(
            run_count=5,
            total_input_tokens=1000,
            total_output_tokens=500,
            total_cost=0.1234,
            per_model={
                "gpt-4o": ModelCost(
                    model="gpt-4o", input_tokens=1000,
                    output_tokens=500, cost=0.1234,
                ),
            },
        )
        comment = generate_pr_comment(cost_report=cost)
        assert "### Cost Summary" in comment
        assert "$0.1234" in comment
        assert "1,500" in comment  # total tokens
        assert "gpt-4o" in comment

    def test_all_sections_combined(self):
        summary = CITestRunSummary(total=10, passed=10)
        gate_report = QualityGateReport(
            results=[GateResult(metric="a", verdict=GateVerdict.PASSED)]
        )
        cost = CostReport(run_count=1, total_cost=0.01)
        comment = generate_pr_comment(
            test_summary=summary,
            gate_report=gate_report,
            cost_report=cost,
        )
        assert "### Test Results" in comment
        assert "### Quality Gates" in comment
        assert "### Cost Summary" in comment

    def test_errors_shown_when_nonzero(self):
        summary = CITestRunSummary(total=5, passed=3, failed=1, errors=1)
        comment = generate_pr_comment(test_summary=summary)
        assert "| Errors | 1 |" in comment

    def test_eval_summary_section(self):
        eval_summary = EvalRunSummary(
            aggregates={
                "task_completion": AggregateResult(
                    metric_name="task_completion",
                    count=10,
                    mean=0.85,
                    median=0.9,
                    stdev=0.1,
                    min_value=0.5,
                    max_value=1.0,
                    pass_rate=0.8,
                ),
            }
        )
        comment = generate_pr_comment(eval_summary=eval_summary)
        assert "### Evaluation Metrics" in comment
        assert "task_completion" in comment
        assert "0.8500" in comment
        assert "80.0%" in comment

    def test_eval_summary_with_regressions(self):
        eval_summary = EvalRunSummary(
            aggregates={
                "accuracy": AggregateResult(
                    metric_name="accuracy", count=5,
                    mean=0.7, median=0.7, stdev=0.1,
                    min_value=0.5, max_value=0.9,
                ),
            },
            regressions=[
                RegressionResult(
                    metric_name="accuracy",
                    current=0.7,
                    baseline=0.9,
                    delta=-0.2,
                    regressed=True,
                    threshold=0.05,
                ),
            ],
        )
        comment = generate_pr_comment(eval_summary=eval_summary)
        assert "Metric regressions detected" in comment
        assert "`accuracy`" in comment
        assert "0.9000" in comment
        assert "0.7000" in comment

    def test_eval_summary_no_regressions_skips_section(self):
        eval_summary = EvalRunSummary(
            aggregates={
                "score": AggregateResult(
                    metric_name="score", count=3,
                    mean=0.95, median=0.95, stdev=0.01,
                    min_value=0.93, max_value=0.97,
                ),
            },
            regressions=[
                RegressionResult(
                    metric_name="score",
                    current=0.95, baseline=0.90,
                    delta=0.05, regressed=False, threshold=0.05,
                ),
            ],
        )
        comment = generate_pr_comment(eval_summary=eval_summary)
        assert "Metric regressions detected" not in comment

    def test_safety_report_section(self):
        report = ComplianceReport(
            total_tests=20,
            total_passed=18,
            total_findings=2,
            categories={
                SafetyCategory.PROMPT_INJECTION: CategorySummary(
                    category=SafetyCategory.PROMPT_INJECTION,
                    total=10,
                    passed=9,
                    failed=1,
                    findings_by_severity={Severity.HIGH: 1},
                ),
                SafetyCategory.PII_LEAKAGE: CategorySummary(
                    category=SafetyCategory.PII_LEAKAGE,
                    total=10,
                    passed=9,
                    failed=1,
                    findings_by_severity={Severity.MEDIUM: 1},
                ),
            },
        )
        comment = generate_pr_comment(safety_report=report)
        assert "### Safety Results" in comment
        assert "90.0%" in comment
        assert "18/20" in comment
        assert "prompt_injection" in comment
        assert "pii_leakage" in comment
        assert "Total findings" in comment

    def test_safety_report_no_critical_shows_checkmark(self):
        report = ComplianceReport(total_tests=5, total_passed=5)
        comment = generate_pr_comment(safety_report=report)
        assert ":white_check_mark:" in comment

    def test_safety_report_critical_shows_warning(self):
        report = ComplianceReport(
            total_tests=5,
            total_passed=3,
            total_findings=2,
            categories={
                SafetyCategory.PROMPT_INJECTION: CategorySummary(
                    category=SafetyCategory.PROMPT_INJECTION,
                    total=5, passed=3, failed=2,
                    findings_by_severity={Severity.CRITICAL: 2},
                ),
            },
        )
        comment = generate_pr_comment(safety_report=report)
        assert ":warning:" in comment

    def test_all_five_sections_combined(self):
        summary = CITestRunSummary(total=10, passed=10)
        eval_summary = EvalRunSummary(
            aggregates={
                "score": AggregateResult(
                    metric_name="score", count=10,
                    mean=0.9, median=0.9, stdev=0.05,
                    min_value=0.8, max_value=1.0,
                ),
            }
        )
        safety = ComplianceReport(total_tests=5, total_passed=5)
        gate_report = QualityGateReport(
            results=[GateResult(metric="a", verdict=GateVerdict.PASSED)]
        )
        cost = CostReport(run_count=1, total_cost=0.01)
        comment = generate_pr_comment(
            test_summary=summary,
            eval_summary=eval_summary,
            safety_report=safety,
            gate_report=gate_report,
            cost_report=cost,
        )
        assert "### Test Results" in comment
        assert "### Evaluation Metrics" in comment
        assert "### Safety Results" in comment
        assert "### Quality Gates" in comment
        assert "### Cost Summary" in comment
