"""PR comment reporter for CI/CD integration.

Generates Markdown tables summarizing test results, quality gate verdicts,
cost breakdown, and safety results for posting as PR comments.

Implements PRD requirement F5.1 (PR comment generation).
"""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Any

from checkagent.ci.quality_gate import GateVerdict, QualityGateReport
from checkagent.core.cost import CostReport

# Lazy imports to avoid circular dependencies — these modules are optional
# and only accessed when the caller provides eval/safety data.
if False:  # TYPE_CHECKING equivalent without importing typing
    from checkagent.eval.aggregate import RunSummary as EvalRunSummary
    from checkagent.safety.compliance import ComplianceReport


def generate_pr_comment(
    *,
    test_summary: RunSummary | None = None,
    gate_report: QualityGateReport | None = None,
    cost_report: CostReport | None = None,
    eval_summary: EvalRunSummary | None = None,
    safety_report: ComplianceReport | None = None,
    title: str = "CheckAgent Test Report",
) -> str:
    """Generate a full Markdown PR comment from test results.

    All parameters are optional — sections are only rendered if data is provided.
    """
    sections: list[str] = []
    sections.append(f"## {title}\n")

    # Overall status badge
    if gate_report is not None:
        if gate_report.passed:
            sections.append("> **Status:** :white_check_mark: All quality gates passed\n")
        else:
            blocked = gate_report.blocked_gates
            sections.append(
                f"> **Status:** :x: {len(blocked)} quality gate(s) blocked\n"
            )

    # Test summary
    if test_summary is not None:
        sections.append(_render_test_summary(test_summary))

    # Eval metrics
    if eval_summary is not None:
        sections.append(_render_eval_summary(eval_summary))

    # Safety
    if safety_report is not None:
        sections.append(_render_safety_report(safety_report))

    # Quality gates
    if gate_report is not None and gate_report.results:
        sections.append(_render_quality_gates(gate_report))

    # Cost
    if cost_report is not None:
        sections.append(_render_cost(cost_report))

    # Footer
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    sections.append(
        f"---\n*Generated by [CheckAgent]"
        f"(https://github.com/checkagent/checkagent) at {timestamp}*"
    )

    return "\n".join(sections)


class RunSummary:
    """Lightweight summary of pytest results for reporting."""

    def __init__(
        self,
        *,
        total: int = 0,
        passed: int = 0,
        failed: int = 0,
        skipped: int = 0,
        errors: int = 0,
        duration_s: float = 0.0,
        regressions: list[str] | None = None,
    ) -> None:
        self.total = total
        self.passed = passed
        self.failed = failed
        self.skipped = skipped
        self.errors = errors
        self.duration_s = duration_s
        self.regressions = regressions or []

    @property
    def pass_rate(self) -> float:
        if self.total == 0:
            return 0.0
        return self.passed / self.total

    def to_dict(self) -> dict[str, Any]:
        return {
            "total": self.total,
            "passed": self.passed,
            "failed": self.failed,
            "skipped": self.skipped,
            "errors": self.errors,
            "duration_s": round(self.duration_s, 2),
            "pass_rate": round(self.pass_rate, 4),
            "regressions": self.regressions,
        }


def _render_test_summary(summary: RunSummary) -> str:
    """Render the test summary section."""
    lines = ["### Test Results\n"]
    lines.append("| Metric | Value |")
    lines.append("|--------|-------|")
    lines.append(f"| Total tests | {summary.total} |")
    lines.append(f"| Passed | {summary.passed} |")
    lines.append(f"| Failed | {summary.failed} |")
    lines.append(f"| Skipped | {summary.skipped} |")
    if summary.errors > 0:
        lines.append(f"| Errors | {summary.errors} |")
    lines.append(f"| Duration | {summary.duration_s:.1f}s |")
    lines.append(f"| Pass rate | {summary.pass_rate:.1%} |")
    lines.append("")

    if summary.regressions:
        lines.append("**Regressions detected:**\n")
        for reg in summary.regressions:
            lines.append(f"- `{reg}`")
        lines.append("")

    return "\n".join(lines)


def _render_eval_summary(summary: EvalRunSummary) -> str:
    """Render the evaluation metrics section."""
    lines = ["### Evaluation Metrics\n"]
    if summary.aggregates:
        lines.append("| Metric | Mean | Median | Pass Rate | Count |")
        lines.append("|--------|------|--------|-----------|-------|")
        for name, agg in sorted(summary.aggregates.items()):
            pass_rate_str = f"{agg.pass_rate:.1%}" if agg.pass_rate is not None else "—"
            lines.append(
                f"| {name} | {agg.mean:.4f} | {agg.median:.4f} | {pass_rate_str} | {agg.count} |"
            )
        lines.append("")

    if summary.regressions:
        regressed = [r for r in summary.regressions if r.regressed]
        if regressed:
            lines.append("**Metric regressions detected:**\n")
            for r in regressed:
                lines.append(
                    f"- `{r.metric_name}`: {r.baseline:.4f} → {r.current:.4f} "
                    f"(Δ {r.delta:+.4f}, threshold {r.threshold:.4f})"
                )
            lines.append("")

    return "\n".join(lines)


def _render_safety_report(report: ComplianceReport) -> str:
    """Render the safety results section."""
    lines = ["### Safety Results\n"]
    icon = ":white_check_mark:" if not report.has_critical_findings else ":warning:"
    rate = report.overall_resistance_rate
    passed, total = report.total_passed, report.total_tests
    lines.append(f"{icon} **Resistance rate:** {rate:.1%} ({passed}/{total})\n")

    if report.categories:
        lines.append("| Category | Tests | Passed | Findings |")
        lines.append("|----------|-------|--------|----------|")
        for cat, cat_summary in sorted(report.categories.items(), key=lambda x: x[0].value):
            findings = sum(cat_summary.findings_by_severity.values())
            lines.append(
                f"| {cat.value} | {cat_summary.total} | {cat_summary.passed} | {findings} |"
            )
        lines.append("")

    if report.total_findings > 0:
        lines.append(f"**Total findings:** {report.total_findings}\n")

    return "\n".join(lines)


def _render_quality_gates(report: QualityGateReport) -> str:
    """Render the quality gates section."""
    lines = ["### Quality Gates\n"]
    lines.append("| Metric | Threshold | Actual | Status |")
    lines.append("|--------|-----------|--------|--------|")

    for result in report.results:
        icon = _verdict_icon(result.verdict)

        if result.threshold is not None:
            direction = ">=" if result.direction == "min" else "<="
            threshold_str = f"{direction} {result.threshold:.2f}"
        else:
            threshold_str = "—"

        actual_str = f"{result.actual:.4f}" if result.actual is not None else "—"
        lines.append(
            f"| {result.metric} | {threshold_str} | {actual_str} | {icon} {result.verdict.value} |"
        )

    lines.append("")
    return "\n".join(lines)


def _render_cost(report: CostReport) -> str:
    """Render the cost summary section."""
    lines = ["### Cost Summary\n"]
    lines.append("| Metric | Value |")
    lines.append("|--------|-------|")
    lines.append(f"| Total cost | ${report.total_cost:.4f} |")
    lines.append(f"| Total tokens | {report.total_tokens:,} |")
    lines.append(f"| Test runs | {report.run_count} |")
    if report.run_count > 0:
        lines.append(f"| Avg cost/run | ${report.avg_cost_per_run:.4f} |")
    lines.append("")

    if report.per_model:
        lines.append("**Per-model breakdown:**\n")
        lines.append("| Model | Tokens | Cost |")
        lines.append("|-------|--------|------|")
        for model, mc in sorted(report.per_model.items()):
            lines.append(f"| {model} | {mc.total_tokens:,} | ${mc.cost:.4f} |")
        lines.append("")

    utilization = report.budget_utilization()
    if utilization:
        lines.append("**Budget utilization:**\n")
        for name, frac in utilization.items():
            pct = frac * 100 if frac is not None else 0
            icon = ":warning:" if pct > 80 else ":white_check_mark:"
            lines.append(f"- {name}: {pct:.0f}% {icon}")
        lines.append("")

    return "\n".join(lines)


def _verdict_icon(verdict: GateVerdict) -> str:
    """Map verdict to a GitHub-compatible emoji."""
    return {
        GateVerdict.PASSED: ":white_check_mark:",
        GateVerdict.WARNED: ":warning:",
        GateVerdict.BLOCKED: ":x:",
        GateVerdict.SKIPPED: ":heavy_minus_sign:",
    }[verdict]
